vscode:
  extensions:
    - tomi.xajssnippets@1.2.0:PmVqVT8AKuS0fNeiILeduQ==
    - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==
    - dsznajder.es7-react-js-snippets@3.1.0:MJ/bfyCCPMdDGtAC1ZzGOQ==